import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import DashHeader from "@/components/dashboard/shell/DashHeader";
import DashSidebar from "@/components/dashboard/shell/DashSideBar";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gray-100">
        <DashHeader />
        <main>
          <DashSidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
